### ISSUE TITLE
Truncate by words

### ISSUE THREAD

**Issue by alzearafat** [ikeikeikeike/phoenix_html_simplified_helpers#4]
Hi @ikeikeikeike 

Thank you for the lib, really helped me :) 
Is there any way it can truncate by words? Instead of chars?

Thank you
Cheers!

**Comment by ikeikeikeike** [comment]
Respond by c9ae327387552523c649972a359560729b3944b5, Its new version [here](https://hex.pm/packages/phoenix_html_simplified_helpers).
