### ISSUE TITLE
Upgrade timex dependency

### ISSUE THREAD

**Issue by udfalkso** [ikeikeikeike/phoenix_html_simplified_helpers#5]
I just got this when trying to install

```
Failed to use "timex" (version 3.1.7) because
  phoenix_html_simplified_helpers (version 0.8.0) requires ~> 2.1 or ~> 2.2
  mix.lock specifies 3.1.7
```

Thanks

**Comment by ikeikeikeike** [comment]
Respond by c9ae327387552523c649972a359560729b3944b5, Its new version [here](https://hex.pm/packages/phoenix_html_simplified_helpers).
