### ISSUE TITLE
Integer.to_char_list/1 is deprecated

### ISSUE THREAD

**Issue by dsandstrom** [ikeikeikeike/phoenix_html_simplified_helpers#7]
I receive a warning when compiling:
> warning: Integer.to_char_list/1 is deprecated, use Integer.to_charlist/1
  lib/phoenix_html_simplified_helpers/number_with_delimiter.ex:6

**Comment by ikeikeikeike** [comment]
Fixed with 4bfd0895a175f27176a2d762e9536f6533811c4d
